prometheus:
  rbac:
    create: true
  podSecurityPolicy:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts: 
      - prometheus.k8s.likens.us
  persistentVolume:
    enabled: true
