ingress.enabled: true
ingress.host: atlantis.likens.us
github.user: scottmlikens
github.token: redacted
github.secret: redacted
repoConfig: |
 ---
 repos:
 - id: /.*/
   apply_requirements: ["workflow"]
   workflow: default
   apply_requireents: ["mergeable"]
   allowed_overrides: ["workflow"]
   allow_custom_workflows: true
