ingress.enabled: true
ingress.host: atlantis.likens.us
repoConfig:
  repos:
    - id: /.*/
    allowed_overrides: ["workflow"]
    apply_requirements: ["mergeable"]
    workflow: default
    allow_custom_workflows: true
