ingress.enabled: true
ingress.host: atlantis.likens.us
github:
  user: foo
  token: bar
  secret: baz
repoConfig: |
 ---
 repos:
 - id: /.*/
   apply_requirements: ["workflow"]
   workflow: default
   apply_requireents: ["mergeable"]
   allowed_overrides: ["workflow"]
   allow_custom_workflows: true
