mimir:
  metaMonitoring:
    serviceMonitor:
      enabled: true
    grafanaAgent:
      enabled: true
      installOperator: true
      metrics:
        additionalRemoteWriteConfigs:
          - url: "http://192.168.1.224:9090/api/v1/write"
