jenkins:
  controller:
    tag: "lts"
    image: "jenkins/jenkins"
    adminSecret: "true"
    adminUser: "admin"
    adminPassword: "temp12345"
    installPlugins: ["kubernetes","workflow-aggregator","git","configuration-as-code","prometheus","blueocean"]
    ingress:
      enabled: true
      hostName: "jenkins.k8s.likens.us"
  
